# Generated by Django 3.1.6 on 2021-03-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsp_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=48)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsrs.artist')),
            ],
        ),
        migrations.AlterField(
            model_name='dsr',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.currency'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='local_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='dsrs.currency'),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(max_length=256)),
                ('usages', models.CharField(max_length=256)),
                ('revenue', models.CharField(max_length=256)),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsrs.dsr')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsrs.recording')),
            ],
        ),
    ]
