# Generated by Django 3.1.6 on 2021-03-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0002_auto_20210323_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='dsr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='record',
        ),
        migrations.AddField(
            model_name='dsr',
            name='recording',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.recording'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='statistics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dsrs.statistics'),
            preserve_default=False,
        ),
    ]
