# Generated by Django 3.1.6 on 2021-03-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0003_auto_20210323_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsr',
            name='recording',
        ),
        migrations.AddField(
            model_name='recording',
            name='dsr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dsr', to='dsrs.dsr'),
            preserve_default=False,
        ),
    ]
