# Generated by Django 3.1.6 on 2021-03-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0004_auto_20210325_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
